/*
* SPDX-FileCopyrightText: Copyright 2025 Arm Limited and/or its affiliates <open-source-office@arm.com>
* SPDX-License-Identifier: Apache-2.0
*/
#version 450

layout (binding = 0) writeonly buffer OUT_DATA {uint out_data[1];};

layout (constant_id = 0) const uint SPEC_CONST = 100500;

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

void main() {
    out_data[0] = SPEC_CONST;
}
